[package]
name = "footer-generator"
version = "0.1.0"
edition = "2021"

[dependencies]
yew = { version = "0.20.0", features = ["csr"] }
stylist = { version = "0.11", features = ["yew_integration","macros",] }
console_log = { version = "0.2.0", features = ["color"] }
log = "0.4.17"
